version: '3.8'

services:
  app:
    build:
      context: .  # Path to the current directory
      dockerfile: Dockerfile  # Name of your Dockerfile
    ports:
      - "9797:9797"  # Exposing backend port
      - "5173:5173"  # Exposing frontend port
    volumes:
      - ./Backend:/app/Backend
      - ./Frontend:/app/Frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
